# Site settings
baseurl = "http://danibram.github.io/"
languageCode = "en-us"
title = "Opensource projects"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = "danibr4m"

canonifyurls = true

[params]
	name = "Daniel Biedma"
	description = "My opensource projects"
	bio = "Developer - Photographer - Consultant"
	# Enter optionally your twitter account
	twitter = "danibram"
	enableRSS = true

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = "https://dbr.io/"
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "Overpowered full-stack developer"
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

    # Social icons style - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/danibram"
    facebook = "https://www.facebook.com/danibram"
    github   = "https://www.github.com/danibram"
    linkedin = "https://www.linkedin.com/in/danielbiedma"
    dbr = "https://dbr.io"
    rss = "./index.xml"
