# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Miligram"
license = "MIT"
licenselink = "https://github.com/danibram//blob/master/LICENSE.md"
description = ""
homepage = "http://danibram.github.io/"
tags = ["", ""]
features = ["", ""]
min_version = 0.14

[author]
  name = "Daniel Biedma"
  homepage = "https://dbr.io"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
